- controller/controller.go
- extension/extension.go
- extension/extension_test.go
- extension/xml_test.go
- server/server_test.go
Fix #3 
This uses a map instead of a slice so that extensions can be looked up to see if there is a match by extension ID.
> Use map for lookup of known extensions

- Gopkg.lock
- Gopkg.toml
- controller/controller.go
- server/server_test.go
This PR does 2 things:
1) Adds a timer to refresh the list of extensions from DynamoDB
2)Adds an API to print all extensions that the server knows about
Since a LOT of clients query for extensions, and the list of extensions is small. It is better to cache the extension list in a map locally and periodically refresh it. 
DynamoDB is populated by a separate Node packaging script here https://github.com/brave/brave-core-crx-packager/commit/842199aa8e8e8127634fdf20e19db1b5aa1fbbc7
> Use DynamoDB for extensions

- Dockerfile
- Makefile
- README.md
Updated ```Dockerfile``` so that when ```docker-compose up``` is used, the ```go-updater``` application will be deployed.
> Fixed Dockerfile in order to deploy a functioning go-updater

- controller/controller.go
- server/server.go
- server/server_test.go
fix https://github.com/brave/go-update/issues/13
`server_tests` fail when components like to Light/Dark theme are updated since it uses real-time data if the aws config is set correctly. Updating the tests to use local data when tests are executed. This avoids confusion on test failure if the aws config is set correctly.
auditors: @bbondy
> Issue 13: Using local test data to avoid test failures on component updates

- extension/extension.go
- extension/xml.go
- server/server_test.go
Fix https://github.com/brave/brave-browser/issues/1319
Component updater expects `appid` and update-status `noupdate` if the component is up to date. If `appid` and `update-status` are not present in the response from the go-updater,  `UpdateCheckResult` for the component is set to `UPDATE_RESPONSE_NOT_FOUND` showing an error on the `brave://components` screen.
(https://cs.chromium.org/chromium/src/components/update_client/update_engine.cc?l=262)
Please feel free to reach out if you have any questions.
auditors: @bsclifton, @bbondy
1. Component Install:
- Open Brave with a clean new profile
2. Component Updates:
3. Individual Updates:
4. New Extensions:
5. Update Extensions (update available) - Wait for Adblock to update
6. Update Error
1. …
> Return appid with an update-status noupdate if component is up to date

- controller/controller.go
- server/server_test.go
CRLSets which is maintained by google will be enabled by default in Brave to handle revoked certificates on all platforms. To prevent any connections to google servers by default we are setting the fallback URL for google extensions and components to componentupdater.brave.com which removes any user identifiable information before forwarding the requests to the google component update server.
More details here: https://github.com/brave/brave-browser/issues/518
auditors: @bbondy, @bsclifton, @diracdeltas
CRLSets PR: https://github.com/brave/brave-core/pull/1581
Feel free to DM if you need more info.
- Before CRLSets
- MacOS: 
- Linux: 
- Windows: 
- After CRLSets
- MacOS: 
- Linux: 
- Windows:
> Issue 15: Set the fallback URL for google extensions/components to componentupdater.brave.com.

- docker-compose-dev.yml
- docker-compose-prod.yml
- docker-compose.yml
- extension/xml.go
- extension/xml_test.go
- server/server_test.go
Hardcoding production S3 buckets in the go-updater code causes problems in dev environments. This change uses `S3_EXTENSIONS_BUCKET_HOST` environment variable to check if `go-updater` is running in production or development environment.
Prod `S3_EXTENSIONS_BUCKET_HOST`: `brave-core-ext.s3.brave.com`
Dev `S3_EXTENSIONS_BUCKET_HOST`: `brave-core-ext.s3.bravesoftware.com`
auditors: @bbondy, @hspencer77, @mihaiplesa 
Automated tests should pass.
> Issue 18: Use dev instances of S3 buckets for components in dev environments

- controller/controller.go
- server/server_test.go
fixes: https://github.com/brave/go-update/issues/20
Instead of going into a redirect loop with `braveRedirect`, setting the fallback URL for extensions to `extensionupdater.brave.com` which serves as the proxy for `clients2.google.com`
> Issue 20: Updating fallback URL for extensions and removing braveRedirects

- controller/controller.go
- extension/extensiontest/extensiontest.go
- extension/json.go
- extension/json_test.go
- extension/utils.go
- extension/xml.go
- extension/xml_test.go
- server/server_test.go
Fix https://github.com/brave/go-update/issues/24
Chromium has decided to finally deprecate the `ProtocolHandlerFactoryXML` in C75. We need to support both XML and JSON parsers till C75 reaches stable. 
For `WebStoreUpdateExtension` - We use the `prodversion` query parameter to verify if the request was for C75 or older version to determine which parser to use
For `UpdateExtension` - We use `json.Unmarshal ` to check if the body is a json request or not.
Detailed test plan here - https://docs.google.com/document/d/1XIlEJ-rudud5GVqwiUbOcwblJsUxJPbbJehlNpwGdqs/edit
> Issue 24: Implement JSON parser for extension and component updates

- Gopkg.lock
- Gopkg.toml
- controller/controller.go
- main.go
- server/server.go
Fix https://github.com/brave/go-update/issues/30
From https://github.com/getsentry/raven-go
> The raven-go SDK is no longer maintained and was superseded by the sentry-go SDK.
Also the `go-update` project on our sentry login was not receiving any events. 
I tested this locally and it is now recording events. 
Please pay special attention to the `Gopkg.lock` in the review as it made some changes that I'm not familiar with.
To deploy I believe `dep ensure` and `make` should be run.
> Init sentry and replace deprecated raven-go with sentry-go

- docker-compose-dev.yml
- docker-compose-prod.yml
- extension/data.go
- extension/extension_test.go
- extension/json.go
- extension/json_test.go
- extension/utils.go
- extension/xml.go
- extension/xml_test.go
- server/server_test.go
> Fix #33: Update endpoint for fetching Tor Client Updater on Mac, Windows and Linux

- Dockerfile
Fix https://github.com/brave/go-update/issues/35
`golangci-lint` is not required in the Dockerfile since lint is not triggered on build.
> Fix 35: Moving lint out of Dockerfile

- server/server.go
Fix #42 
Request logs are flooding the disk space on EC2 instances. This PR gates the request logs behind an environment variable. Currently, we disable the environment variable in prod and dev environment.
If needed, we can enable request logging at the load balancer.
> Fix 42: Request logging is gated behind an environment variable

- .travis.yml
- controller/controller.go
- server/server_test.go
Fix #45 
* With Browser
* Navigate to https://bitmovin.com/demos/drm
* Allow `Widevine` and verify the request for update is sent to `update.googleapis.com`
* Ensure that the download is triggered from `*.gvt1.com` or `*.dl.google.com`
* With curl:
```
% curl -Ls -o /dev/null -w '%{url_effective}' -d '{"request":{"@os":"mac","@updater":"","acceptformat":"crx2,crx3","app":[{"appid":"oimompecagnajdejgnnjijobebaeigek","enabled":true,"installsource":"ondemand","ping":{"r":-2},"updatecheck":{},"version":"0.0.0.0"}],"arch":"x64","dedup":"cr","domainjoined":false,"hw":{"physmemory":16},"lang":"","nacl_arch":"x86-64","os":{"arch":"x86_64","platform":"Mac OS X","version":"10.15.5"},"prodchannel":"stable","prodversion":"83.1.12.20","protocol":"3.1","requestid":"{67dd796c-ac2d-46f9-a56d-6495e7c92640} …
```
> Fix 45: Do not proxy requests for Widevine

- docker-compose-dev.yml
- docker-compose-prod.yml
closes #https://github.com/brave/devops/issues/3238
will only deploy to production when all buckets are in synced and jenkins ext pipelines are updated
> update ext buckets

- docker-compose-dev.yml
- docker-compose-prod.yml
- extension/data.go
- extension/extension_test.go
- extension/utils.go
Fix #49 
```
1. $ curl -Ls -d '{"request":{"@os":"mac","@updater":"","acceptformat":"crx2,crx3","app":[{"appid":"nljcddpbnaianmglkpkneakjaapinabi","enabled":true,"installsource":"ondemand","ping":{"r":-2},"updatecheck":{},"version":"0.0.0.0"}],"arch":"x64","dedup":"cr","domainjoined":false,"hw":{"physmemory":16},"lang":"","nacl_arch":"x86-64","os":{"arch":"x86_64","platform":"Mac OS X","version":"10.15.5"},"prodchannel":"stable","prodversion":"83.1.12.20","protocol":"3.1","requestid":"{67dd796c-ac2d-46f9-a56d-6495e7c92640}","sessionid":"{fd35f289-fb9a-4a7c-8acf-9576b1d0c5eb}","updaterchannel":"stable","updaterversion":"83.1.12.20"}}' -H "Content-Type: application/json" -X POST http://localhost:8192/extensions
)]}'
{"response":{"protocol":"3.1","server":"prod","app":[{"appid":"nljcddpbnaian …
```
> Fix #49: Download IPFS component from ipfs/ipfs-dev.bravesoftware.com

- controller/controller.go
- extension/utils.go
Get the componentupdater URL from the environemnt. For testing development & staging environments for `componentupdater`.
Mainly for our new architecture changes for `componentupdater`. See: https://github.com/brave/security/issues/634#issuecomment-966477156
> Adding the ability to get the component updater URL from env

- controller/controller.go
- extension/extension.go
- extension/extension_test.go
- extension/json_test.go
- extension/xml_test.go
- server/server_test.go
Under heavy-load our application was panicing with `fatal error: concurrent map read and map write` due to the extensions map refresh goroutine writing whilst a read was occurring.
> Ensuring concurrent extension map access is safe

- extension/utils.go
New component added in https://github.com/brave/brave-browser/issues/1138
Build&upload job https://ci.brave.com/job/brave-core-ext-tor-pluggable-transports-publish/
Added Tor pluggable transports extensions ids because they hosted on tor.bravesoftware.com
> Tor pluggable transports extensions ids

- controller/controller.go
- extension/extension.go
- omaha/v4/protocol_test.go
- omaha/v4/response.go
- omaha/v4/response_test.go
> fix: Add required fields to Omaha v4 response

- .gitignore
- controller/controller.go
- go.mod
- go.sum
- server/server.go
- server/server_test.go
Follow-up to recently closed #260 
CHANGELOG: https://github.com/go-chi/chi/blob/master/CHANGELOG.md
Noteworthy change:
> deprecate & remove chi.ServerBaseContext in favour of stdlib http.Server#BaseContext
> chore: Update go-chi to v5

- controller/controller.go
- extension/extension.go
- extension/extension_test.go
- omaha/v3/response.go
- omaha/v3/response_test.go
- omaha/v4/response.go
- omaha/v4/response_test.go
- server/server_test.go
Resolves #262
- the `app` array in response object must be rendered even if the client-claimed version is newer than the server one ([docs](https://source.chromium.org/chromium/chromium/src/+/main:docs/updater/protocol_4.md#:~:text=status%3A%20Indicates%20the%20outcome%20of%20the%20updatecheck.%20Servers%20must%20always%20send%20a%20value%20here.%20Known%20values%3A)) (resolves #262)
- the response must include information about every requested ID (applies to requests with more than one ID; [docs](https://source.chromium.org/chromium/chromium/src/+/main:docs/updater/protocol_4.md;bpv=0#:~:text=If%20an%20application%20appears%20in%20the%20request%2C%20it%20must%20have%20a%20corresponding%20acknowledgement%20in%20the%20response.))
Simplified JSON request:
```json
{
"request": {
"apps": [
{ …
```
> fix: Add graceful handling for component version mismatch and invalid IDs
